global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alertmanager'
