version: '3'

services:

  zipkin:
    image: openzipkin/zipkin:2.22.0
    ports: 
      - "9411:9411"
    networks:
      - front_net
      - back_net

  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - back_net

networks:
  front_net:
  back_net:
