---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
# NodePort видится снаружи, может быть в диапозоне 30000-32767
  type: NodePort
# type: LoadBalancer
  ports:
  - port: 9292
#   nodePort: 32092
    protocol: TCP
    targetPort: 9292
  selector:
    app: reddit
    component: ui
