---
- name: Deploy Docker
  hosts: all
  become: true
  tasks:
  - name: redis container
    docker_container:
      name: reddit
      image: spracs/test-reddit:1.0
      state: started
      detach: yes
      ports:
      - "9292:9292"
